### ISSUE TITLE
seems broken cannot download book

### ISSUE THREAD

**Issue by muelli** [groggi/springer-dl#1]
python3 springer-dl.py http://www.springer.com/gp/book/9783658011512 foo

```
Traceback (most recent call last):
  File "springer-dl.py", line 260, in <module>
    main()
  File "springer-dl.py", line 256, in main
    extract_content(session, args.url, args.output)
  File "springer-dl.py", line 204, in extract_content
    document_type = root_page_parsed.find('div', id='content').find('div', class_='document').get('id')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by groggi** [comment]
I may look into the problem. However, this project is not maintained anymore (see README) as SpringerLink provides a download for the whole book nowadays. If you have access to the book you should be able to download it completely as one PDF after clicking on "Read this book on SpringerLink".
